# This is a sample build configuration for JavaScript.
# Check our guides at https://confluence.atlassian.com/x/14UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: node:12-buster

clone:
  depth: full # SonarCloud scanner needs the full history to assign issues properly

definitions:
  caches:
    sonar: ~/.sonar/cache
  steps:
    - step: &build-test-sonarcloud
            name: Build, test and analyze on SonarCloud
            caches:
              - sonar
              - node
            script:
              - make install
              - make test
              - pipe: sonarsource/sonarcloud-scan:1.2.1
                variables:
                  EXTRA_ARGS: '
                    -Dsonar.sources=functions,repositories,services
                    -Dsonar.tests=__tests__
                    -Dsonar.exclusions=node_modules/,**/*.test.*
                    -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info'

    - step: &check-quality-gate-sonarcloud
            name: Check the Quality Gate on SonarCloud
            script:
              - pipe: sonarsource/sonarcloud-quality-gate:0.1.4

    - step: &deploy-aws-qa
            name: Deploy to QA stage
            deployment: QA
            caches:
              - node
            script:
              - touch .env
              - make install
              - npx sls deploy -s ${STAGE}

    - step: &deploy-aws-prod
            name: Deploy to Production stage
            deployment: Production
            caches:
              - node
            script:
              - touch .env
              - make install
              - npx sls deploy -s ${STAGE}

pipelines:
  branches:
    master:
      - step: *build-test-sonarcloud
      - step: *check-quality-gate-sonarcloud
      - step: *deploy-aws-prod
    develop:
      - step: *build-test-sonarcloud
      - step: *check-quality-gate-sonarcloud
      - step: *deploy-aws-qa
  pull-requests:
    '**':
      - step: *build-test-sonarcloud
      - step: *check-quality-gate-sonarcloud
