# This is a sample build configuration for JavaScript.
# Check our guides at https://confluence.atlassian.com/x/14UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: node:12
clone:
  depth: full # SonarCloud scanner needs the full history to assign issues properly

definitions:
  caches:
    sonar: ~/.sonar/cache
    nodemodules: ~/app/node_modules
  steps:
    - step: &build-test-sonarcloud
            name: Build, test and analyze on SonarCloud
            caches:
              - nodemodules
              - sonar
              - node
            script:
              - make install
              - make test
              - pipe: sonarsource/sonarcloud-scan:1.0.1
                 variables:
                 EXTRA_ARGS: '
                  -Dsonar.sources=app
                  -Dsonar.tests=app/__tests__
                  -Dsonar.exclusions=app/node_modules/,app/lib/resources/**/*,**/*.test.*
                  -Dsonar.javascript.lcov.reportPaths=app/coverage/lcov.info'
    - step: &check-quality-gate-sonarcloud
            name: Check the Quality Gate on SonarCloud
            script:
              - pipe: sonarsource/sonarcloud-quality-gate:0.1.3
    - step: &deploy-aws-qa
            name: Deploy to QA stage
            deployment: QA
            caches:
              - nodemodules
            script:
              - make install
              - cd app && npx sls deploy -s ${STAGE}
    - step: &deploy-aws-prod
            name: Deploy to Production stage
            deployment: Production
            caches:
              - nodemodules
            script:
              - make install
              - cd app && npx sls deploy -s ${STAGE}

pipelines:
  branches:
    master:
      - step: *build-test-sonarcloud
      - step: *check-quality-gate-sonarcloud
      # - step: *deploy-aws-prod
    develop:
      - step: *build-test-sonarcloud
      - step: *check-quality-gate-sonarcloud
      # - step: *deploy-aws-qa
  pull-requests:
    '**':
      - step: *build-test-sonarcloud
      - step: *check-quality-gate-sonarcloud
